```python
#🧨a= set('a','b') -> 집합을 만들때 주의!!
print(set(['a','b']))
print({'a', 'b', 'c'})


```

    {'b', 'a'}
    {'b', 'c', 'a'}
    

## set 값 비교


```python
word1, word2 = set("eat"), set(["eat"])  ##{'a', 'e', 't'} {'eat'}
word3 = set("ate")

print(word1 == word3)
print(''.join(word1) == ''.join(word3))
```

    True
    True
    


```python
x = {{'a', 'b', 'c'}}
x.add({"a","b"})
```


    ---------------------------------------------------------------------------

    TypeError                                 Traceback (most recent call last)

    Input In [5], in <cell line: 1>()
    ----> 1 x = {{'a', 'b', 'c'}}
          2 x.add({"a","b"})
    

    TypeError: unhashable type: 'set'



```python
#add는 한개씩
x = {'a', 'b', 'c'}
x.add("d")
print(x)
```

    {'b', 'c', 'a'}
    


```python
#update는 여러개
x = {'a', 'b', 'c'}
x.update({"a","b","d"})
print(x)
```

    {'b', 'c', 'd', 'a'}
    


```python
x = {('a', 'b', 'c')}
x.update({"a","b"})
print(x)
```

    {('a', 'b', 'c'), 'a', 'b'}
    

https://blockdmask.tistory.com/451
